import type { AppData } from "./types";

const now = new Date().toISOString();
const groupId = "group-1";

export const initialData: AppData = {
  practiceAreas: [
    { id: "pa-1", name: "מקרקעין", is_active: true },
    { id: "pa-2", name: "משפחה וירושה", is_active: true },
    { id: "pa-3", name: "ליטיגציה אזרחית", is_active: true },
    { id: "pa-4", name: "מסחרי", is_active: true },
    { id: "pa-5", name: "חברות", is_active: true },
    { id: "pa-6", name: "עבודה", is_active: true },
    { id: "pa-7", name: "נזיקין", is_active: true },
    { id: "pa-8", name: "חדלות פירעון", is_active: true },
    { id: "pa-9", name: "תכנון ובנייה", is_active: true },
    { id: "pa-10", name: "מיסוי", is_active: true },
    { id: "pa-11", name: "פלילי", is_active: true },
    { id: "pa-12", name: "מנהלי", is_active: true },
    { id: "pa-13", name: "קניין רוחני", is_active: true },
    { id: "pa-14", name: "הייטק", is_active: true },
    { id: "pa-15", name: "דיני מושבים וקיבוצים", is_active: true },
    { id: "pa-16", name: "אחר", is_active: true },
  ],
  regions: [
    { id: "r-1", name: "חיפה", is_active: true },
    { id: "r-2", name: "קריות", is_active: true },
    { id: "r-3", name: "טבעון", is_active: true },
    { id: "r-4", name: "יקנעם", is_active: true },
    { id: "r-5", name: "עמק יזרעאל", is_active: true },
    { id: "r-6", name: "עפולה", is_active: true },
    { id: "r-7", name: "פרדס חנה", is_active: true },
    { id: "r-8", name: "חדרה", is_active: true },
    { id: "r-9", name: "צפון", is_active: true },
    { id: "r-10", name: "מרכז", is_active: true },
    { id: "r-11", name: "שרון", is_active: true },
    { id: "r-12", name: "אחר", is_active: true },
  ],
  membershipPlans: [
    {
      id: "mp-1",
      name: "שנתי",
      price: 3200,
      period: "yearly",
      description: "חברות שנתית",
      is_active: true,
      internal_notes: "",
    },
    {
      id: "mp-2",
      name: "רבעוני",
      price: 875,
      period: "quarterly",
      description: "חברות רבעונית",
      is_active: true,
      internal_notes: "",
    },
    {
      id: "mp-3",
      name: "מייסדים",
      price: 0,
      period: "yearly",
      description: "מחיר מייסדים — חברות שנתית ראשונה ללא עלות למצטרפים הראשונים",
      is_active: true,
      internal_notes: "",
    },
    {
      id: "mp-4",
      name: "חודשי",
      price: 150,
      period: "monthly",
      description: "חברות חודשית",
      is_active: false,
      internal_notes: "",
    },
  ],
  systemContent: [
    {
      id: "sc-1",
      key: "welcome",
      title: "ברוכים הבאים",
      content: "ברוכים הבאים ל-Forum Lexellence — פורום מקצועי לעורכי דין המחויבים לאיכות, לשיתוף פעולה ולצמיחה מקצועית.",
      updated_at: now,
    },
    {
      id: "sc-2",
      key: "vision",
      title: "חזון הפורום",
      content: "ליצור קהילה משפטית איכותית, מבוססת אמון, שמקדמת שיתופי פעולה מקצועיים והפניות בתום לב.",
      updated_at: now,
    },
    {
      id: "sc-3",
      key: "rules",
      title: "כללי הפורום",
      content: `## דיסקרטיות
כל המידע בפורום הוא חסוי ואינו ניתן לשיתוף מחוץ לקהילה.

## אתיקה מקצועית
יש לנהוג בכל עת בהתאם לכללי האתיקה המקצועית של לשכת עורכי הדין.

## כבוד הדדי
יש לכבד את חברי הפורום ולהימנע מהתנהגות פוגענית.

## איסור שימוש לרעה בפרטי חברים
אין להשתמש בפרטי הקשר של חברים למטרות שיווקיות או מסחריות ללא אישור.

## הפניות בתום לב
הפניות יינתנו באמונה ובתום לב, תוך שמירה על האינטרסים של הלקוח.

## השתתפות פעילה
מצופה מחברי הפורום להשתתף במפגשים ולתרום לקהילה.

## שמירה על מידע פנימי
מידע שנאמר במפגשים או בקבוצה אינו לשיתוף חיצוני.`,
      updated_at: now,
    },
    {
      id: "sc-4",
      key: "join",
      title: "הצטרפות",
      content: "ההצטרפות לפורום מותנית בראיון אישי ואישור מנהל הקבוצה.",
      updated_at: now,
    },
    {
      id: "sc-5",
      key: "referrals_help",
      title: "הסבר על הפניות",
      content: "דווחו על הפניות שנתתם או קיבלתם כדי לעקוב אחר שיתופי הפעולה בקבוצה. המידע גלוי רק לכם, לחבר הקשור ולמנהלי הקבוצה.",
      updated_at: now,
    },
    {
      id: "sc-6",
      key: "requests_help",
      title: "הסבר על בקשות מקצועיות",
      content: "פרסמו בקשות מקצועיות כשאתם מחפשים שיתוף פעולה, מומחיות או ייעוץ מחברי הפורום.",
      updated_at: now,
    },
    {
      id: "sc-7",
      key: "footer",
      title: "Footer",
      content: "Forum Lexellence © 2026 — כל הזכויות שמורות",
      updated_at: now,
    },
    {
      id: "sc-8",
      key: "contact",
      title: "יצירת קשר",
      content: "admin@forumlexellence.co.il | 04-1234567",
      updated_at: now,
    },
    {
      id: "sc-login-1",
      key: "login_brand_name",
      title: "שם המותג",
      content: "Forum Lexellence",
      updated_at: now,
    },
    {
      id: "sc-login-2",
      key: "login_brand_subtitle",
      title: "כתובית מותג",
      content: "הפורום המקצועי לעורכי דין",
      updated_at: now,
    },
    {
      id: "sc-login-3",
      key: "login_main_text",
      title: "טקסט ראשי",
      content: "קהילה משפטית איכותית, מבוססת אמון, שמקדמת שיתופי פעולה מקצועיים, הפניות בתום לב וצמיחה מקצועית — במקום אחד.",
      updated_at: now,
    },
    {
      id: "sc-login-4",
      key: "login_feature_1",
      title: "תכונה 1",
      content: "ניהול קבוצות וחברים",
      updated_at: now,
    },
    {
      id: "sc-login-5",
      key: "login_feature_2",
      title: "תכונה 2",
      content: "אירועים ומפגשים מקצועיים",
      updated_at: now,
    },
    {
      id: "sc-login-6",
      key: "login_feature_3",
      title: "תכונה 3",
      content: "הפניות ושיתופי פעולה",
      updated_at: now,
    },
    {
      id: "sc-login-7",
      key: "login_feature_4",
      title: "תכונה 4",
      content: "בקשות מקצועיות ומסמכים",
      updated_at: now,
    },
    {
      id: "sc-login-8",
      key: "login_title",
      title: "כותרת התחברות",
      content: "התחברות",
      updated_at: now,
    },
    {
      id: "sc-login-9",
      key: "login_subtitle",
      title: "תת-כותרת התחברות",
      content: "ברוכים הבאים. נא להתחבר לחשבונך.",
      updated_at: now,
    },
    {
      id: "sc-login-10",
      key: "register_title",
      title: "כותרת הרשמה",
      content: "הרשמה לפורום",
      updated_at: now,
    },
    {
      id: "sc-login-11",
      key: "register_subtitle",
      title: "תת-כותרת הרשמה",
      content: "יצירת חשבון חדש בפורום.",
      updated_at: now,
    },
  ],
  groups: [
    {
      id: groupId,
      name: "קבוצת חיפה והקריות",
      region: "חיפה",
      description: "קבוצת עורכי דין מקצועית באזור חיפה והקריות, המתכנסת פעמיים בחודש.",
      group_admin_id: "user-admin",
      status: "active",
      meeting_frequency: "פעמיים בחודש",
      default_meeting_day: "יום שלישי",
      rules: "השתתפות פעילה במפגשים, דיווח על הפניות, שמירה על דיסקרטיות.",
      notes: "",
      created_at: now,
      updated_at: now,
    },
  ],
  users: [
    {
      id: "user-super",
      full_name: "דנה כהן",
      email: "admin@lexellence.demo",
      phone: "050-1111111",
      password: "Lexellence123!",
      role: "super_admin",
      group_id: null,
      firm_name: "Lexellence Management",
      title: "מנהלת מערכת",
      years_experience: 15,
      practice_areas: ["pa-12"],
      region: "r-1",
      bio: "מנהלת הפורום המקצועי.",
      website: "",
      linkedin: "",
      profile_image: "",
      membership_status: "active",
      payment_status: "not_required",
      referral_seeking: "",
      collaboration_interests: "",
      internal_notes: "",
      created_at: now,
      updated_at: now,
    },
    {
      id: "user-admin",
      full_name: "עו״ד רון לוי",
      email: "groupadmin@lexellence.demo",
      phone: "050-2222222",
      password: "Lexellence123!",
      role: "group_admin",
      group_id: groupId,
      firm_name: "לוי ושות׳",
      title: "שותף",
      years_experience: 18,
      practice_areas: ["pa-3", "pa-7"],
      region: "r-1",
      bio: "עו״ד ליטיגציה אזרחית ונזיקין, מנהל קבוצת חיפה.",
      website: "https://levi-law.co.il",
      linkedin: "https://linkedin.com/in/ronlevi",
      profile_image: "",
      membership_status: "active",
      payment_status: "paid",
      referral_seeking: "תיקי נזיקין מורכבים",
      collaboration_interests: "שיתופי פעולה בליטיגציה",
      internal_notes: "",
      created_at: now,
      updated_at: now,
    },
    {
      id: "user-member",
      full_name: "עו״ד מיכל אברהם",
      email: "member@lexellence.demo",
      phone: "050-3333333",
      password: "Lexellence123!",
      role: "member",
      group_id: groupId,
      firm_name: "אברהם משרד עורכי דין",
      title: "עורכת דין",
      years_experience: 8,
      practice_areas: ["pa-1", "pa-9"],
      region: "r-2",
      bio: "מתמחה במקרקעין ותכנון ובנייה.",
      website: "",
      linkedin: "https://linkedin.com/in/michalabraham",
      profile_image: "",
      membership_status: "active",
      payment_status: "paid",
      referral_seeking: "תיקי תכנון ובנייה",
      collaboration_interests: "שיתופי פעולה במקרקעין",
      internal_notes: "",
      created_at: now,
      updated_at: now,
    },
    {
      id: "user-member-2",
      full_name: "עו״ד יוסי מזרחי",
      email: "yossi@example.co.il",
      phone: "050-4444444",
      password: "member123",
      role: "member",
      group_id: groupId,
      firm_name: "מזרחי ושות׳",
      title: "שותף",
      years_experience: 12,
      practice_areas: ["pa-4", "pa-5"],
      region: "r-1",
      bio: "דיני חברות ומסחר.",
      website: "https://mizrahi-law.co.il",
      linkedin: "",
      profile_image: "",
      membership_status: "active",
      payment_status: "paid",
      referral_seeking: "עסקאות M&A",
      collaboration_interests: "ייעוץ מסחרי",
      internal_notes: "",
      created_at: now,
      updated_at: now,
    },
    {
      id: "user-member-3",
      full_name: "עו״ד שירה גולן",
      email: "shira@example.co.il",
      phone: "050-5555555",
      password: "member123",
      role: "member",
      group_id: groupId,
      firm_name: "גולן משפחה",
      title: "עורכת דין",
      years_experience: 6,
      practice_areas: ["pa-2"],
      region: "r-3",
      bio: "משפחה וירושה.",
      website: "",
      linkedin: "",
      profile_image: "",
      membership_status: "active",
      payment_status: "founder_price",
      referral_seeking: "תיקי ירושה מורכבים",
      collaboration_interests: "גישור משפחתי",
      internal_notes: "",
      created_at: now,
      updated_at: now,
    },
  ],
  events: [
    {
      id: "event-1",
      title: "מפגש חודשי — שיתופי פעולה מקצועיים",
      group_id: groupId,
      date: "2026-07-15",
      start_time: "18:30",
      end_time: "20:30",
      location: "מלון דan כרמל, חיפה",
      meeting_type: "physical",
      zoom_link: "",
      description: "מפגש חודשי לדיון בשיתופי פעולה ועדכונים מקצועיים.",
      agenda: "18:30 — התכנסות\n19:00 — הרצאה: שיתופי פעולה בליטיגציה\n20:00 — דיון פתוח",
      visibility: "group_only",
      status: "published",
      created_by: "user-admin",
      created_at: now,
      updated_at: now,
    },
    {
      id: "event-2",
      title: "סדנת מיסוי לעורכי דין",
      group_id: groupId,
      date: "2026-06-20",
      start_time: "17:00",
      end_time: "19:00",
      location: "Zoom",
      meeting_type: "zoom",
      zoom_link: "https://zoom.us/j/123456789",
      description: "סדנה מקצועית בנושא מיסוי.",
      agenda: "17:00 — פתיחה\n17:30 — הרצאה\n18:30 — שאלות ותשובות",
      visibility: "all_forum",
      status: "completed",
      created_by: "user-admin",
      created_at: now,
      updated_at: now,
    },
  ],
  eventRSVPs: [
    {
      id: "rsvp-1",
      event_id: "event-1",
      user_id: "user-member",
      status: "attending",
      created_at: now,
      updated_at: now,
    },
    {
      id: "rsvp-2",
      event_id: "event-1",
      user_id: "user-member-2",
      status: "maybe",
      created_at: now,
      updated_at: now,
    },
  ],
  referrals: [
    {
      id: "ref-1",
      type: "given",
      created_by: "user-member",
      related_user_id: "user-member-2",
      group_id: groupId,
      practice_area: "pa-4",
      description: "הפניתי לקוח בנושא חוזה מסחרי.",
      status: "in_progress",
      date: "2026-06-01",
      notes: "",
      created_at: now,
      updated_at: now,
    },
    {
      id: "ref-2",
      type: "received",
      created_by: "user-member-2",
      related_user_id: "user-member",
      group_id: groupId,
      practice_area: "pa-1",
      description: "קיבלתי הפניה לתיק מקרקעין.",
      status: "completed",
      date: "2026-05-15",
      notes: "התיק הסתיים בהצלחה",
      created_at: now,
      updated_at: now,
    },
  ],
  requests: [
    {
      id: "req-1",
      title: "מחפש עו״ד מומחה לחדלות פירעון",
      description: "יש לי לקוח שזקוק לייצוג בתיק חדלות פירעון מורכב.",
      practice_area: "pa-8",
      urgency: "urgent",
      visibility: "my_group",
      status: "open",
      created_by: "user-member-3",
      group_id: groupId,
      created_at: now,
      updated_at: now,
    },
    {
      id: "req-2",
      title: "שאלה מקצועית — עסקת מקרקעין",
      description: "מישהו יכול לייעץ לגבי מיסוי במכירת דירה?",
      practice_area: "pa-1",
      urgency: "normal",
      visibility: "all_forum",
      status: "open",
      created_by: "user-member",
      group_id: groupId,
      created_at: now,
      updated_at: now,
    },
  ],
  requestComments: [
    {
      id: "rc-1",
      request_id: "req-2",
      user_id: "user-member-2",
      comment: "אני יכול לעזור, שלחי לי פרטים במייל.",
      created_at: now,
    },
  ],
  documents: [
    {
      id: "doc-1",
      title: "סיכום מפגש מאי 2026",
      type: "meeting_summary",
      group_id: groupId,
      content: "דיון בשיתופי פעולה בין חברי הקבוצה. הוחלט על מפגש נוסף ביולי.",
      file_url: "",
      uploaded_by: "user-admin",
      meeting_date: "2026-05-20",
      decisions: "לקיים מפגש נוסף ב-15.7",
      tasks: "כל חבר ידווח על הפניה אחת לפחות",
      created_at: now,
      updated_at: now,
    },
    {
      id: "doc-2",
      title: "כללי הקבוצה",
      type: "rules",
      group_id: groupId,
      content: "כללי התנהגות והשתתפות בקבוצת חיפה.",
      file_url: "",
      uploaded_by: "user-admin",
      created_at: now,
      updated_at: now,
    },
  ],
  announcements: [
    {
      id: "ann-1",
      title: "מפגש יולי — אנא אשרו הגעה",
      content: "המפגש הבא יתקיים ב-15.7. אנא אשרו הגעה דרך עמוד האירועים.",
      audience: "specific_group",
      group_id: groupId,
      is_important: true,
      show_on_homepage: true,
      created_by: "user-admin",
      created_at: now,
      updated_at: now,
    },
    {
      id: "ann-2",
      title: "ברוכים הבאים ל-Forum Lexellence",
      content: "שמחים לקבל אתכם לפורום המקצועי שלנו.",
      audience: "all",
      group_id: null,
      is_important: false,
      show_on_homepage: true,
      created_by: "user-super",
      created_at: now,
      updated_at: now,
    },
  ],
  candidates: [
    {
      id: "cand-1",
      full_name: "עו״ד אלon ברק",
      phone: "050-6666666",
      email: "alon@example.co.il",
      region: "r-2",
      practice_areas: ["pa-6"],
      years_experience: 5,
      bio: "עו״ד דיני עבודה.",
      seeking: "רשת מקצועית ושיתופי פעולה",
      status: "new",
      group_id: groupId,
      notes: "",
      created_at: now,
    },
    {
      id: "cand-2",
      full_name: "עו״ד נועה שapira",
      phone: "050-7777777",
      email: "noa@example.co.il",
      region: "r-1",
      practice_areas: ["pa-10"],
      years_experience: 10,
      bio: "מומחית למיסוי.",
      seeking: "קהילה מקצועית איכותית",
      status: "in_conversation",
      group_id: groupId,
      notes: "שיחה ראשונית בוצעה",
      created_at: now,
    },
  ],
};

export const DEMO_CREDENTIALS = [
  { email: "admin@lexellence.demo", password: "Lexellence123!", label: "מנהל מערכת" },
  { email: "groupadmin@lexellence.demo", password: "Lexellence123!", label: "מנהל קבוצה" },
  { email: "member@lexellence.demo", password: "Lexellence123!", label: "חבר פורום" },
];
